name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish
        uses: tuliren/publish-gitbook@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
